### ISSUE TITLE
Latest LocalyticsXamarin nuget package relies on Xamarin.Forms and LocalyticsSample projects

### ISSUE THREAD

**Issue by justintoth** [localytics/localytics-xamarin#47]
I just removed all nuget packages from my Xamarin iOS Project to start fresh re-adding them to the project file itself instead of using a packages.json file. When I added the LocalyticsXamarin nuget package (5.8.0), it gave build errors related to a LocalyticsXamarinForms.cs file:

```
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(20,20): Error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?) (CS0234) (com.rpr.mobile.ios.lib)
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(7,7): Error CS0246: The type or namespace name 'LocalyticsSample' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (com.rpr.mobile.ios.lib)
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(71,71): Error CS0246: The type or namespace name 'IPlatform' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (com.rpr.mobile.ios.lib)
```

When inspecting this file, it depends on including the Xamarin.Forms nuget package, which doesn't make sense when working on a vanilla Xamarin.iOS project. It also relies on LocalyticsSample, which isn't found so obviously isn't being included in the nuget package. Can someone please resolve these issues and release a buildable LocalyticsXamarin nuget package?

**Comment by thomasvidas** [comment]
@justintoth I'll be sure to get this is fixed in our next release. Expect the fix sometime next week for version 5.9.0.

**Comment by thomasvidas** [comment]
@justintoth, we just released a new version of our Xamarin SDK. Does this fix your issue? If it doesn't can you give me a small reproducible example?

**Comment by justintoth** [comment]
Hi @thomasvidas, sorry for the delay in responding, I wasn't receiving email notifications. This is still an issue with LocalyticsXamarin 6.0.0. LocalyticsXamarinForms.cs is included in the package, which has this attribute at the top:

`[assembly: Xamarin.Forms.Dependency(typeof(LocalyticsXamarin.Shared.LocalyticsXamarinForms))]`

It's not appropriate for this class to be included in the Xamarin iOS nuget package, as Xamarin Forms is a different platform.

A repro sample shouldn't be necessary since you should be able to see that class in the project just as easily as I can. I ended up forking your repo, removing the class, and generating my own custom nuget package to get past this block.
